export {default as CadastroAtleta} from "./CadastroAtleta";
export {default as Chamada} from "./Chamada";
export {default as ErrorPage} from "./ErrorPage";
export {default as Home} from "./Home";
export {default as HomeAtleta} from "./HomeAtleta";
export {default as HomeProfessor} from "./HomeProfessor";
export {LoginAtleta} from "./LoginAtleta";
export {LoginGestor} from "./LoginGestor";
export {LoginProfessor} from "./LoginProfessor";
export {default as ProfileSelect} from "./ProfileSelect";