export {default as CadastroAtleta} from "./CadastroAtleta";
export {default as Chamada} from "./Chamada";
export {default as ErrorPage} from "./ErrorPage";
export {default as Home} from "./Home";
export {default as HomeAtleta} from "./HomeAtleta";
export {default as LoginAtleta} from "./LoginAtleta";
export {default as LoginGestor} from "./LoginGestor";
export {default as LoginProfessor} from "./LoginProfessor";
export {default as ProfileSelect} from "./ProfileSelect";